### ISSUE TITLE
Tooltip is not appearing for Stock Events

### ISSUE THREAD

**Issue by ajit-kumar-azad** [walkingtree/chartsly#44]
Tooltip is not appearing for various stock events - Bonus, Split, Dividend, Rights. Please refer to http://chartslyuat.walkingtree.in/#basic-event-combination as an example.

**Comment by ranjit-battewad** [comment]
Fixed the tooltip issues, now all the stock events showing tooltip properly.

**Comment by DivyaAasireddy** [comment]
Tooltip is displaying successfully for the Bonus, Split, Dividend, Rights stock events.So, closing the issue.

![tooltip](https://cloud.githubusercontent.com/assets/13447247/11524590/e3bf202a-98f1-11e5-9b08-3b14458f4220.png)

![rights tooltip](https://cloud.githubusercontent.com/assets/13447247/11524539/7e7e56fe-98f1-11e5-8c30-0cdf8ba7ed2e.png)

![didvidend tootip](https://cloud.githubusercontent.com/assets/13447247/11524544/899475be-98f1-11e5-985d-7dd4f4741896.png)
