### ISSUE TITLE
Annotation image is not proper

### ISSUE THREAD

**Issue by ajit-kumar-azad** [walkingtree/chartsly#45]
When I try to add an annotation on http://chartslyuat.walkingtree.in/#basic-annotation the annotation image appears to be smaller than expected.

**Comment by ranjit-battewad** [comment]
Fixed, now annotation images are appearing fine.

**Comment by DivyaAasireddy** [comment]
Annotation image displayed is matching with existing annotation images on the app, working as expected and QA passed. So, closing the issue.

![annotation image](https://cloud.githubusercontent.com/assets/13447247/11524282/942ec86e-98ef-11e5-8738-8e25076577ec.png)

**Comment by ajit-kumar-azad** [comment]
Looks good
