### ISSUE TITLE
Sencha Cmd v6 6.2.1.29 and Ext JS 6.0.0.640 giving error

### ISSUE THREAD

**Issue by ajit-kumar-azad** [walkingtree/chartsly#46]
I checked out the code from repo and copied Ext JS 6.0.0.640 SDK to StockCharts/extjs6x and extjs6-kitchensink/ext folders, ran sencha app refresh and ran sencha app build from extjs6-kitchensink folder AND the build failed with the following error:

.....
.....
[WRN] Reference to undeclared variable $fa-var-minus-square => /Users/ajitkumar/git/chartsly/extjs6-kitchensink/ext/classic/theme-neutral/sass/var/tree/View.scss:140
[WRN] Sass compilation encountered 131 warning(s)
[LOG] Build error for /Users/ajitkumar/git/chartsly/extjs6-kitchensink/build/temp/production/KS/slicer-temp/KS-example.scss
[ERR] Reference to undeclared variable : $fa_var_caret_right
[ERR] raise@phantomjs://platform/fashion-phantomjs.js:5:14335
raise@phantomjs://code/phantom-sass-compiler.js:106:30
value@phantomjs://platform/fashion-phantomjs.js:5:42179
[native code]
anonymous
fn@phantomjs://platform/fashion-phantomjs.js:5:40613
fn@phantomjs://platform/fashion-phantomjs.js:3:54246
func@phantomjs://platform/fashion-phantomjs.js:2:49208
phantomjs://platform/fashion-phantomjs.js:2:27278
value@phantomjs://platform/fashion-phantomjs.js:4:4229
value@phantomjs://platform/fashion-phantomjs.js:2:27127
build@phantomjs://code/phantom-sass-compiler.js:111:26
global code@phantomjs://code/phantom-sass-compiler.js:153:10
Exiting with code 3
raise@phantomjs://platform/fashion-phantomjs.js:5:14335
raise@phantomjs://code/phantom-sass-compiler.js:106:30
value@phantomjs://platform/fashion-phantomjs.js:5:42179
[native code]
anonymous
fn@phantomjs://platform/fashion-phantomjs.js:5:40613
fn@phantomjs://platform/fashion-phantomjs.js:3:54246
func@phantomjs://platform/fashion-phantomjs.js:2:49208
phantomjs://platform/fashion-phantomjs.js:2:27278
value@phantomjs://platform/fashion-phantomjs.js:4:4229
value@phantomjs://platform/fashion-phantomjs.js:2:27127
build@phantomjs://code/phantom-sass-compiler.js:111:26
global code@phantomjs://code/phantom-sass-compiler.js:153:10
[ERR] 
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.ExBuild: PhantomJS sass build exited with code : 3
[ERR] 	at org.apache.tools.ant.taskdefs.Sequent
[ERR] ial.execute(Sequential.java:68)
[ERR] 
[ERR] Total time: 27 seconds
[ERR] The following error occurred while executing this line:
/Users/ajitkumar/git/chartsly/extjs6-kitchensink/.sencha/app/build-impl.xml:334: The following error occurred while executing this line:
/Users/ajitkumar/git/chartsly/extjs6-kitchensink/.sencha/app/slice-impl.xml:360: The following error occurred while executing this line:
/Users/ajitkumar/git/chartsly/extjs6-kitchensink/.sencha/app/slice-impl.xml:361: The following error occurred while executing this line:
/Users/ajitkumar/git/chartsly/extjs6-kitchensink/.sencha/app/slice-impl.xml:104: com.sencha.exceptions.ExBuild: PhantomJS sass build exited with code : 3

Though there are no errors in application as well as theme build but phantomJS gives up. 
[build_log.txt](https://github.com/walkingtree/chartsly/files/646941/build_log.txt)

Anything that you already faced? What could be going wrong?

I have attached the complete log of the work for reference.

**Comment by ajit-kumar-azad** [comment]
The application seems to work but the styles are not in place.
![bad style](https://cloud.githubusercontent.com/assets/3363210/21113348/1f42cc66-c05e-11e6-813f-344c9f386d76.png)

**Comment by ajit-kumar-azad** [comment]
Ran sencha app upgrade pointing to the SDK folder and could get the build working. However, the sample code is not visible.
![code_missing](https://cloud.githubusercontent.com/assets/3363210/21115978/6e6c20f8-c068-11e6-838b-81da120b6012.png)

I think I am going to upgrade the whole project to the latest version of ExtJS SDK - 6.2.1 and the corresponding Cmd version.

Will close this issue for now and report 6.2.1 specific issue in case I come across one.

**Comment by Quansatoooo** [comment]
i have a same issue  =(((( . help me pls. thank u
